services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - ./config:/config
      - /srv/sig-web/public:/public
    environment:
      - ACME_AGREE=true
      - CADDY_WATCH=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"

networks:
  default:
    driver: bridge